databases:
  - name: postgres
    ipAllowList: []
    plan: free
    region: singapore
services:
  - type: web
    name: rails
    env: ruby
    plan: free
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_HOST
        sync: false
    runtime: ruby
  - type: redis
    name: redis
    region: singapore
    ipAllowList: [ ]
    plan: free
    maxmemoryPolicy: noeviction
version: "1"